### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by bliz937** [jamietyger/AfricanGenomeArchive#1]
So to get things on track, lets create a road map of sorts to help have an action plan and a goal to reach.

- [x] Discuss what requirements the project has
- [x] Identify what is outstanding
- [x] Plan/design goals/deadlines/tasks to complete project
- [x] Create project/milestone on github
- [x] Create issues for outstanding tasks, and assign them to the project/milestones
